//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Collections.Generic;
    
    public partial class NN_comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NN_comment()
        {
            this.NN_report = new HashSet<NN_report>();
        }
    
        public long rowNum { get; set; }
        public string rowID { get; set; }
        public string commentID { get; set; }
        public string userID { get; set; }
        public string newsID { get; set; }
        public string commentContent { get; set; }
        public string fatherCommentID { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> commentTime { get; set; }
    
        public virtual NN_newsItem NN_newsItem { get; set; }
        public virtual NN_user NN_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NN_report> NN_report { get; set; }
    }
}
