//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Collections.Generic;
    
    public partial class NN_report
    {
        public long rowNum { get; set; }
        public string rowID { get; set; }
        public string userID { get; set; }
        public string reportID { get; set; }
        public System.DateTime reportTimeDateTime { get; set; }
        public string reason { get; set; }
        public Nullable<int> category { get; set; }
        public int disposeStatus { get; set; }
        public string newsID { get; set; }
        public string commentID { get; set; }
    
        public virtual NN_comment NN_comment { get; set; }
        public virtual NN_newsItem NN_newsItem { get; set; }
        public virtual NN_user NN_user { get; set; }
    }
}
