//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Collections.Generic;
    
    public partial class NN_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NN_user()
        {
            this.NN_apply = new HashSet<NN_apply>();
            this.NN_comment = new HashSet<NN_comment>();
            this.NN_like = new HashSet<NN_like>();
            this.NN_newsItem = new HashSet<NN_newsItem>();
            this.NN_report = new HashSet<NN_report>();
            this.NN_star = new HashSet<NN_star>();
        }
    
        public long rowNum { get; set; }
        public string rowID { get; set; }
        public string userID { get; set; }
        public string userName { get; set; }
        public byte[] profile { get; set; }
        public System.DateTime registerDateTime { get; set; }
        public string password { get; set; }
        public bool gender { get; set; }
        public System.DateTime birth { get; set; }
        public int type { get; set; }
        public string newsAgencyID { get; set; }
        public bool status { get; set; }
        public string remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NN_apply> NN_apply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NN_comment> NN_comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NN_like> NN_like { get; set; }
        public virtual NN_NewsAgency NN_NewsAgency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NN_newsItem> NN_newsItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NN_report> NN_report { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NN_star> NN_star { get; set; }
    }
}
